// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fayitgdiehhddsyvubwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZheWl0Z2RpZWhoZGRzeXZ1YndyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NDkzNTEsImV4cCI6MjA3MzIyNTM1MX0.iEqdk7IUVhodZ3IaZcI0BIMjD5fIQ-whIuF23JtRUYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});